// Auto-generated by crawl.py
window.historyData = {
  "2026-03-18": {
    "macro": [
      {
        "title": "대출 갚느라 허덕여도 '외식은 포기안해'…뒤로 가는 한국",
        "link": "https://www.hankyung.com/article/2026031805601",
        "source": "한국경제",
        "tier": "A",
        "date": "2026-03-18"
      },
      {
        "title": "항공 유류할증료 3배↑…4인가족 유럽여행 200만원 추가 ‘폭탄’",
        "link": "https://www.donga.com/news/Culture/article/all/20260318/133556722/2",
        "source": "동아일보",
        "tier": "S",
        "date": "2026-03-17"
      },
      {
        "title": "[사설] 팬데믹 때로 치솟은 청년 실업률 , 국가 창업지원 서둘러야",
        "link": "https://www.khan.co.kr/article/202603181810001",
        "source": "경향신문",
        "tier": "A",
        "date": "2026-03-17"
      }
    ]
  },
  "2026-03-19": {
    "macro": [
      {
        "title": "[임성현 특파원의 월스트리트 인사이트] 커지는 미국 경제 불확실성...차...",
        "link": "https://www.mk.co.kr/article/11992144",
        "source": "매일경제",
        "tier": "B",
        "date": "2026-03-18"
      },
      {
        "title": "미 연준 ‘금리 한차례 더 인하’ 전망 유지했지만…전쟁 장기화 땐 ‘...",
        "link": "https://www.hani.co.kr/arti/economy/economy_general/1250088.html",
        "source": "한겨레",
        "tier": "A",
        "date": "2026-03-18"
      },
      {
        "title": "연준, 이란 전쟁에 금리 인하 물 건너갔나…한은도 7연속 동결 전망",
        "link": "https://www.etoday.co.kr/news/view/2567170",
        "source": "",
        "tier": "D",
        "date": "2026-03-18"
      },
      {
        "title": "美 '매파 동결'에 한은 동결 장기화…중동 변수에 통화정책 불확실성↑",
        "link": "https://www.news1.kr/economy/trend/6106636",
        "source": "뉴스1",
        "tier": "B",
        "date": "2026-03-18"
      },
      {
        "title": "가계대출 정책 한달째 '표류' … 은행은 '금리 카드', 실수요자는 '이중...",
        "link": "https://biz.newdaily.co.kr/site/data/html/2026/03/19/2026031900126.html",
        "source": "뉴데일리",
        "tier": "C",
        "date": "2026-03-19"
      },
      {
        "title": "코스피, 5,800선 붕괴... 국제 긴장 속 원 / 달러 환율 급등",
        "link": "https://www.tokenpost.kr/news/market/341200",
        "source": "",
        "tier": "D",
        "date": "2026-03-18"
      },
      {
        "title": "불타는 중동 에너지 인프라…숨 막히는 세계 경제",
        "link": "https://www.yna.co.kr/view/AKR20260319098200009?input=1195m",
        "source": "연합뉴스",
        "tier": "S",
        "date": "2026-03-19"
      },
      {
        "title": "중동 사태 불확실성에 미 연준 금리 동결…“올해 인하 1번 가능”",
        "link": "https://news.kbs.co.kr/news/pc/view/view.do?ncd=8512826&ref=A",
        "source": "KBS",
        "tier": "S",
        "date": "2026-03-18"
      }
    ],
    "ebike_delivery": [
      {
        "title": "쿠팡 무료배송 인상에 비판 '봇물'...\"탈팡 손실 소비자에 전가\"",
        "link": "https://www.ytn.co.kr/_ln/0102_202603191317012895",
        "source": "YTN",
        "tier": "A",
        "date": "2026-03-18"
      }
    ]
  }
};
