// Auto-generated by crawl.py
window.historyData = {
  "2026-03-18": {
    "macro": [
      {
        "title": "대출 갚느라 허덕여도 '외식은 포기안해'…뒤로 가는 한국",
        "link": "https://www.hankyung.com/article/2026031805601",
        "source": "한국경제",
        "tier": "A",
        "date": "2026-03-18"
      },
      {
        "title": "항공 유류할증료 3배↑…4인가족 유럽여행 200만원 추가 ‘폭탄’",
        "link": "https://www.donga.com/news/Culture/article/all/20260318/133556722/2",
        "source": "동아일보",
        "tier": "S",
        "date": "2026-03-17"
      },
      {
        "title": "[사설] 팬데믹 때로 치솟은 청년 실업률 , 국가 창업지원 서둘러야",
        "link": "https://www.khan.co.kr/article/202603181810001",
        "source": "경향신문",
        "tier": "A",
        "date": "2026-03-17"
      }
    ]
  }
};
